import './../src/variables.global.js';
import { expect, test } from '@jest/globals';

test('variables.global', () => {
    expect(is_array).not.toBeUndefined();
    expect(is_bool).not.toBeUndefined();
    expect(is_class).not.toBeUndefined();
    expect(is_number).not.toBeUndefined();
    expect(is_float).not.toBeUndefined();
    expect(is_double).not.toBeUndefined();
    expect(is_int).not.toBeUndefined();
    expect(is_integer).not.toBeUndefined();
    expect(is_long).not.toBeUndefined();
    expect(is_null).not.toBeUndefined();
    expect(is_numeric).not.toBeUndefined();
    expect(is_object).not.toBeUndefined();
    expect(is_string).not.toBeUndefined();
    expect(is_scalar).not.toBeUndefined();
    expect(is_symbol).not.toBeUndefined();
    expect(is_undefined).not.toBeUndefined();
    expect(is_callable).not.toBeUndefined();
    expect(arrval).not.toBeUndefined();
    expect(boolval).not.toBeUndefined();
    expect(floatval).not.toBeUndefined();
    expect(doubleval).not.toBeUndefined();
    expect(empty).not.toBeUndefined();
    expect(get_debug_type).not.toBeUndefined();
    expect(gettype).not.toBeUndefined();
    expect(intval).not.toBeUndefined();
    expect(isset).not.toBeUndefined();
    expect(strval).not.toBeUndefined();
    expect(print_r).not.toBeUndefined();
    expect(var_dump).not.toBeUndefined();
    expect(serialize).not.toBeUndefined();
    expect(settype).not.toBeUndefined();
    expect(is_contract).not.toBeUndefined();
    expect(is_iterable).not.toBeUndefined();
    expect(is_countable).not.toBeUndefined();
    expect(objval).not.toBeUndefined();
    expect(unserialize).not.toBeUndefined();
    expect(var_export).not.toBeUndefined();
});
